apiVersion: v1
kind: Service
metadata:
  name: dp-1-web-svc
  # namespace: integration
spec:
  selector:
    app.kubernetes.io/instance: cp4i-dp-1
  ports:
    - name: dpconsole
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: calchttp
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: calchttps
      protocol: TCP
      port: 7043
      targetPort: 7043     
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dp1console
  # namespace: integrationclear
spec:
  to:
    kind: Service
    name: dp-1-web-svc
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: passthrough
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: calc-http
  # namespace: integration
spec:
  to:
    kind: Service
    name: dp-1-web-svc
    weight: 100
  port:
    targetPort: 8081
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: calc-https
  # namespace: integration
spec:
  to:
    kind: Service
    name: dp-1-web-svc
    weight: 100
  port:
    targetPort: 7043
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: v1
kind: Secret
metadata:
  name: dp-admin-credentials
   #namespace: integration
data:
  password: YWRtaW4=
type: Opaque
---
apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: dp-1
  # namespace: integration
spec:
  license:
    accept: true
    license: L-RJON-CCAT5F
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
#  storage:
#  - type: persistent
#    path: /opt/ibm/datapower/drouter/config
#    size: 10Gi
#    class: ibmc-block-gold
#    volumeMode: Block
  domains:
  - name: "RRdomain"
    certs:
    - certType: "usrcerts"
      secret: "mycerts"
    dpApp:
      config:
      - "rrdomain-config"
      local:
      - "rrdomain-local"
  - name: "default" 
    dpApp:
      config:
      - "default-config"
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: dp-admin-credentials
  version: 10.5-lts
  replicas: 1
